apiVersion: skaffold/v2beta1
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: wimtk
      context: ./wimtk
      sync:
        infer:
          - '*.go'
          - '**/*.go'
  local:
    push: false
    concurrency: 1
deploy:
  kubeContext: docker-desktop
  helm:
    releases:
      - name: wimtk
        chartPath: charts/wimtk
        namespace: wimtk
        values:
          image.repository: wimtk
  