apiVersion: v1
kind: Pod
metadata:
  name: pod-unready
spec:
  containers:
  - name: readyness
    image: k8s.gcr.io/busybox
    args:
    - /bin/sh
    - -c
    - sleep 600
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
